### ISSUE TITLE
用的啥录屏软件，挺溜的，求推荐

### ISSUE THREAD

**Issue by hackware1993** [D-clock/ScratchView#2]

**Comment by D-clock** [comment]
GifCam

**Comment by hackware1993** [comment]
@D-clock 我也是用的这个，但是录制久了gif好大，为毛你这个gif这么小

**Comment by D-clock** [comment]
@hackware1993 我开Android虚拟机录制的，估计是这个原因吧，原先用真机连到电脑录制的时候，gif图也是有点大的。
