### ISSUE TITLE
ACTION_MOVE的时候每次都调用erase()函数是不是太浪费系统资源了？

### ISSUE THREAD

**Issue by DearZack** [D-clock/ScratchView#3]
我觉得在ACTION_UP的时候去调用一下就好了。
我的理解是，erase()函数目的就是去判断一下刮奖有没有结束，完全可以只在ACTION_UP的时候去调用，而且在move的时候跳出了一个中奖结果用户体验也不太好，还是抬手后再判断比较好。

我试了下，在我的测试机mate8中，刮5%的情况下。
原来的思路CPU要26S后才会计算完所有的东西，而新的思路是抬手后的两秒。
内存倒区别不大。
详情见下面两图：
![1](https://cloud.githubusercontent.com/assets/17618134/18416024/a6d60af2-7839-11e6-8f32-51db5220fb17.png)
ACTION_MOVE的时候每次都调用erase()函数
![2](https://cloud.githubusercontent.com/assets/17618134/18416026/aac43fee-7839-11e6-98a0-90463bd3ba38.png)
ACTION_UP的时候调用

**Comment by D-clock** [comment]
@DearZack erase()函数目的是刮去图层，onErase()函数才是判断是否结束，我觉得你这个思路不错，我优化下！

**Comment by D-clock** [comment]
@DearZack 代码已优化，感谢提出宝贵的建议！
